const express=require('express')
const app= express()
const mongoose=require('mongoose')
const bodyParser=require('body-parser')
var jsonParser = bodyParser.json()
mongoose.connect('mongodb://localhost:27017/Student', { useNewUrlParser: true })
const db=mongoose.connection
db.on('error',(error)=>console.log(error))
db.once('open',()=>console.log("DB connected"))
app.use(express.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
const apiRoute=require('./routes/api')
app.use('/api',apiRoute)
app.listen(3000,()=>console.log("server started"))